### PR TITLE
Local storage

### PR DESCRIPTION
**Pull request by sajid-munawar**
- Implemented the following interactions:
  - When the user changes the content of any input field, the data is saved to the local storage.
  - When the user loads the page, if there is any data in the local storage the input fields are pre-filled with this data.
- Used the following data model:
  - You must create a single JavaScript object with all the data from the entire form and save it in local storage. Do not create one local storage entry per input field.

### CODE REVIEW

**Review by sja-thedude — COMMENTED** [review]
## Invalid Code Review Request ❌

Hi @sajid-munawar, This is @sja-thedude your code reviewer.

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

You have submitted a project, that doesn't have commits from both members in your pair programming group. This is a pair programming project which requires commits from both members.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by sajid-munawar** [comment]
@sja-thedude Partners are not responding. requested to success if they change partners.

**Comment by sja-thedude** [comment]
> @sja-thedude Partners are not responding. requested to success if they change partners.

Hi, @sajid-munawar You should have mentioned in the Pull request that partners are not responding then I could have viewed your project. You can submit again!

**Comment by sajid-munawar** [comment]
@sja-thedude submit again. Please review.

**Review by codepantha — APPROVED** [review]
Hi @sajid-munawar 👋,

## STATUS: APPROVED ✔️  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



### Highlights ⭐ 
✔️ Descriptive PR
✔️ Meaningful commit messages
✔️ Linter checks
✔️ Professional README

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
